package_assets: on

javascripts:
  rails:
    - public/javascripts/rails/prototype.js
    - public/javascripts/rails/effects.js
    - public/javascripts/rails/controls.js
    - public/javascripts/rails/dragdrop.js
    - public/javascripts/rails/rails.js

  wizard:
    - public/javascripts/*.js

  catalogue:
    - public/javascripts/rangeslider.min.js
    - public/javascripts/jquery.dataTables.min.js
    - public/javascripts/catalogue.js

stylesheets:
  wizard:
    - public/stylesheets/reset.css
  form:
    - public/stylesheets/main.css
    - public/stylesheets/usages.css
    - public/stylesheets/usages.selectSlider.css
    - public/stylesheets/usages.labelCheckbox.css
    - public/stylesheets/usages.tabbedForm.css
    - public/javascripts/waitpopup.js
  result:
    - public/stylesheets/result.css

  catalogue:
    - public/stylesheets/reset.css
    - public/stylesheets/catalogue.css