package_assets: always

javascripts:
  rails:
    - public/javascripts/rails/prototype.js
    - public/javascripts/rails/effects.js
    - public/javascripts/rails/control.js
    - public/javascripts/rails/dragdrop.js
    - public/javascripts/rails/rails.js
  
  wizard:
    - public/javascripts/*.js

stylesheets:
  wizard:
    - public/stylesheets/reset.css
  form:
    - public/stylesheets/main.css
    - public/stylesheets/usages.css
    - public/stylesheets/usages.selectSlider.css
    - public/stylesheets/usages.labelCheckbox.css
    - public/stylesheets/usages.tabbedForm.css
  result:
    - public/stylesheets/result.css
