package_assets: on

javascripts:
  rails:
    - public/javascripts/rails/prototype.js
    - public/javascripts/rails/effects.js
    - public/javascripts/rails/controls.js
    - public/javascripts/rails/dragdrop.js
    - public/javascripts/rails/rails.js

  home:
    - public/javascripts/jquery.ulslide.js
    - public/javascripts/home.js

  form:
    - public/javascripts/usages.answerMultichoice.js
    - public/javascripts/usages.labelCheckbox.js
    - public/javascripts/usages.selectSlider.js
    - public/javascripts/usages.tabbedForm.js
    - public/javascripts/usages_form.js
    - public/javascripts/waitpopup.js

  result:
    - public/javascripts/jquery.tablesorter.min.js
    - public/javascripts/jquery.ae.image.resize.min.js
    - public/javascripts/result.js

  catalogue:
    - public/javascripts/rangeslider.min.js
    - public/javascripts/jquery.dataTables.min.js
    - public/javascripts/catalogue.js

  product:
    - public/javascripts/jquery.ae.image.resize.min.js
    - public/javascripts/product.js


stylesheets:
  reset:
    - public/stylesheets/reset.css

  header_and_footer:
    - public/stylesheets/header.css
    - public/stylesheets/footer.css

  home:
    - public/stylesheets/home.css

  form:
    - public/stylesheets/main.css
    - public/stylesheets/usages.css
    - public/stylesheets/usages.selectSlider.css
    - public/stylesheets/usages.labelCheckbox.css
    - public/stylesheets/usages.tabbedForm.css
  result:
    - public/stylesheets/result.css

  catalogue:
    - public/stylesheets/catalogue.css

  product:
    - public/stylesheets/product.css

  basic:
    - public/stylesheets/basic_page.css
