gamer:
  usage1:
    usage_id: 1
    weight_for_user: 50
    is_selected: FALSE

  usage2:
    usage_id: 2
    weight_for_user: 50
    is_selected: FALSE

  usage3:
    usage_id: 3
    weight_for_user: 10
    is_selected: TRUE

  usage4:
    usage_id: 4
    weight_for_user: 10
    is_selected: FALSE

  usage5:
    usage_id: 5
    weight_for_user: 10
    is_selected: TRUE

  usage6:
    usage_id: 6
    weight_for_user: 50
    is_selected: FALSE

  usage7:
    usage_id: 7
    weight_for_user: 50
    is_selected: FALSE

  usage8:
    usage_id: 8
    weight_for_user: 50
    is_selected: FALSE

  usage9:
    usage_id: 9
    weight_for_user: 100
    is_selected: FALSE

  usage10:
    usage_id: 10
    weight_for_user: 100
    is_selected: FALSE

  usage11:
    usage_id: 11
    weight_for_user: 100
    is_selected: TRUE

  usage12:
    usage_id: 12
    weight_for_user: 50
    is_selected: FALSE

  usage13:
    usage_id: 13
    weight_for_user: 50
    is_selected: FALSE

  usage14:
    usage_id: 14
    weight_for_user: 20
    is_selected: TRUE

  usage15:
    usage_id: 15
    weight_for_user: 20
    is_selected: FALSE

  usage16:
    usage_id: 16
    weight_for_user: 20
    is_selected: FALSE

  usage17:
    usage_id: 17
    weight_for_user: 20
    is_selected: TRUE

  usage18:
    usage_id: 18
    weight_for_user: 0
    is_selected: TRUE

  usage19:
    usage_id: 19
    weight_for_user: 20
    is_selected: TRUE

  usage20:
    usage_id: 20
    weight_for_user: 0
    is_selected: true
  usage1:
    usage_id: 1
    weight_for_user: 50
    is_selected: FALSE

  usage2:
    usage_id: 2
    weight_for_user: 50
    is_selected: FALSE

  usage3:
    usage_id: 3
    weight_for_user: 10
    is_selected: TRUE

  usage4:
    usage_id: 4
    weight_for_user: 10
    is_selected: FALSE

  usage5:
    usage_id: 5
    weight_for_user: 10
    is_selected: TRUE

  usage6:
    usage_id: 6
    weight_for_user: 50
    is_selected: FALSE

  usage7:
    usage_id: 7
    weight_for_user: 50
    is_selected: FALSE

  usage8:
    usage_id: 8
    weight_for_user: 50
    is_selected: FALSE

  usage9:
    usage_id: 9
    weight_for_user: 100
    is_selected: FALSE

  usage10:
    usage_id: 10
    weight_for_user: 100
    is_selected: FALSE

  usage11:
    usage_id: 11
    weight_for_user: 100
    is_selected: TRUE

  usage12:
    usage_id: 12
    weight_for_user: 50
    is_selected: FALSE

  usage13:
    usage_id: 13
    weight_for_user: 50
    is_selected: FALSE

  usage14:
    usage_id: 14
    weight_for_user: 20
    is_selected: TRUE

  usage15:
    usage_id: 15
    weight_for_user: 20
    is_selected: FALSE

  usage16:
    usage_id: 16
    weight_for_user: 20
    is_selected: FALSE

  usage17:
    usage_id: 17
    weight_for_user: 20
    is_selected: TRUE

  usage18:
    usage_id: 18
    weight_for_user: 0
    is_selected: TRUE

  usage19:
    usage_id: 19
    weight_for_user: 20
    is_selected: TRUE

  usage20:
    usage_id: 20
    weight_for_user: 0
    is_selected: true
